### ISSUE TITLE
Remove node modules file and create .gitignore

### ISSUE THREAD

**Issue by Seniru** [AshutoshAgrawal2004/Agar.io#1]
I saw that you have included node modules in your repository.  But generally adding them to repo is discouraged and should be added to the .gitignore to reduce cloning and pulling time. 
Further you can add extra dependencies to package.json

If you like I could work in this @AshutoshAgrawal2004

**Comment by AshutoshAgrawal2004** [comment]
Thanks for reminding me. But will it not affect my heroku deployment.

I would love to have a helping hand.
I am sorry I have abandoned this project already.

**Comment by Seniru** [comment]
@AshutoshAgrawal2004 oh I do not know that you have abandoned this project. And removing node modules from the repo wont the heroku deployment. And I'll close this issue because you are not maintaining this anymore :)
